version: "3"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
  random-number-server:
    image: aidandj/nats-random-number-guesser-server
    command: "python server.py"
  random-number-client:
    image:  aidandj/nats-random-number-guesser-client
    command: tail -f /dev/null

networks:
  default:
    external:
      name: nats