name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Create the network
    - name: create network
      run: docker network create nats

    # Brings up the containers. And builds them
    - name: up
      run: docker-compose -f docker-compose-dev.yml up -d

    # Runs a set of commands using the runners shell
    - name: Execute python client
      run: docker exec nats-random-number-guesser_random-number-client_1 python client.py
